### ISSUE TITLE
Style attributes not formatted properly

### ISSUE THREAD

**Issue by splodingsocks** [mbylstra/html-to-elm#5]
Inline styles aren't currently formatted properly.

Input:

```html
<div style="background-color: red;"></div>
```

Current output

```elm
div [ style "background-color: red;" ]
    []
```

Expected output

```elm
div [ style [("background-color", "red") ]
    []
```

Thanks!

**Comment by mbylstra** [comment]
Ah, that's something hadn't considered, which would need some parsing to do properly. For now, I'm using 

```
div [ attribute "style" "background-color: red;" ]
    []
```

which should at least compile

**Comment by mbylstra** [comment]
I've opened https://github.com/mbylstra/html-to-elm/issues/6 to address an alternative where the style function is used.

**Comment by splodingsocks** [comment]
Sounds good, thanks!
