### ISSUE TITLE
Does not parse single quote values

### ISSUE THREAD

**Issue by victorlcampos** [mbylstra/html-to-elm#8]
![image](https://cloud.githubusercontent.com/assets/1539610/12078255/a399a3f8-b1f1-11e5-9960-179381cbe188.png)

**Comment by mbylstra** [comment]
It looks like the issue is actually with the parser failing to parse single quotes (not to do with the class property). This example will work if you use double quotes for the value of `class`:

```html
<body>	
  <div class="hello">
    <h1>Hello world</h1>
  </div>
</body>

```
output:
```elm
body []
    [ div [ class "hello" ]
        [ h1 []
            [ text "Hello world" ]
        ]
    ]
```

I've changed the issue title to reflect this.

**Comment by victorlcampos** [comment]
Hi, thx.
I will take a look on this problem and send pr

**Comment by mbylstra** [comment]
No problem. The HTML parsing code is a bit hairy I'm afraid. It was first time I've written a parser, so it was a bit of a learning curve as I was learning Elm at the same time. It's not very well documented. One day I hope to rewrite it so that it can be used more generally, or just use a better parser library that someone else has written. Let me know if you have any questions. The failure to parse single quotes was just laziness on my behalf, as single quotes aren't used so often in HTML.

**Comment by mbylstra** [comment]
If you do have a go at it, the line you'll need to look at is at https://github.com/mbylstra/html-to-elm/blob/master/elm-src/HtmlParser/HtmlParserRawAst.elm#L56.

**Comment by victorlcampos** [comment]
Yes,
it's my first time with elm. How can I run this? =|

**Comment by mbylstra** [comment]
If you clone the repo, you can do:

`elm reactor`

then go to http://localhost:8000/website/index.html in your browser.

You can compile using `gulp elm` or `gulp watch` (you need gulp installed and you need to run `npm install` first from within the repo directory).

**Comment by victorlcampos** [comment]
Sry @mbylstra, I have to go out now, I'm try to understand, but not successfully.
If you fix this, plx mark me to see how.

**Comment by mbylstra** [comment]
Fixed. If you look at https://github.com/mbylstra/html-to-elm/commit/8f3e0727ce83225fdc4b501f7cd63fecb306937b, the fix should be reasonably self-exaplanatory. (Ignore the code in elm.js and website/js/Main.js - that's just the compiled output).


The function
```elm
createParseAnyFunction
         [ parseDoubleQuotationMarkIgnore
         , parseSingleQuotationMarkIgnore
         ]
``
will parse either a single quote or a double quote, and discard it.

Well, the fix isn't completely correct. It will permit "class'  (a mixture of single quotes and double quotes), but it's an improvement.

**Comment by victorlcampos** [comment]
I did not understood why (DoubleQuotationMark, "\"|\'") it wasn't enough

**Comment by mbylstra** [comment]
Yes, that should also work.

**Comment by victorlcampos** [comment]
I tried this, but i got an error...
Late i print it here

**Comment by victorlcampos** [comment]
![image](https://cloud.githubusercontent.com/assets/1539610/12078954/67cdf056-b20d-11e5-987d-395ad46fd285.png)

**Comment by mbylstra** [comment]
I could get the regex to work with  `"(\"|\')"`, but I'm not sure why the brackets in the regex are necessary.

**Comment by victorlcampos** [comment]
Thx, u are doing a great job 😊
